### ISSUE TITLE
AWS Consoler

### ISSUE THREAD

**Issue by Techbrunch** [Hacking-the-Cloud/hackingthe.cloud#108]
First of all, I really like the documentation :)

Thanks to you I discovered (or rediscovered I'm not sure) the tool AWS Consoler.

I think the requirements to use the tool should be added, if I understood correctly they are either:

- being able to call `sts:GetFederationToken`
- or `sts:AssumeRole` with a known role

**Comment by Frichetten** [comment]
Added. Thanks for opening the issue!
