### ISSUE TITLE
Update link to Pacu

### ISSUE THREAD

**Issue by amkuipers** [Hacking-the-Cloud/hackingthe.cloud#162]
On page: https://hackingthe.cloud/aws/enumeration/enum_iam_user_role/
The github link to the pacu module gives a 404, and might have been moved.
Found the module at other path, but please verify if this is the one.

https://github.com/RhinoSecurityLabs/pacu/tree/master/modules/iam__enum_roles
https://github.com/RhinoSecurityLabs/pacu/tree/master/pacu/modules/iam__enum_roles

**Comment by Frichetten** [comment]
Hey there, yep, you are correct. It looks like it has been moved to that second URL you provided. Would you like to submit a PR? No pressure, I would be happy to as well.

**Comment by amkuipers** [comment]
Please change.

**Comment by Frichetten** [comment]
This is fixed in #171. Thank you @amkuipers for pointing this out!
