### ISSUE TITLE
Docker Build for mkdocs fails

### ISSUE THREAD

**Issue by julianwieg** [Hacking-the-Cloud/hackingthe.cloud#209]
Hi,
sorry, I would not call myself a developer so hopefully this is not something totally silly and a 'user fault' by me.

I cloned the repo locally on my ubuntu machine and ran    docker build -t mkdocs-material .    however it fails with:
```
f860f95a24e2: Pull complete 

a1dee26347e0: Pull complete 

Digest: sha256:7346fbc9c31ac7af1c577db0f2301ba25d24ff076a15a4e049f1b8c29840b746

Status: Downloaded newer image for squidfunk/mkdocs-material:latest
 ---> 566a49fd70f9

Step 2/3 : RUN pip install mkdocs-awesome-pages-plugin
 ---> Running in 2cb15d5aa13f

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f886fa9bd90>: Failed to establish a new connection: [Errno -3] Try again')': /simple/mkdocs-awesome-pages-plugin/

etc.
The command '/bin/sh -c pip install mkdocs-awesome-pages-plugin' returned a non-zero code: 1

```

**Comment by Frichetten** [comment]
Hey Julian, based on this error `Failed to establish a new connection: [Errno -3] Try again` it sounds like a networking issue trying to reach the pip servers to download the packages. Have you tried again in case it was a temporary network blip? Or are you using any time of DNS based ad-blocking like Pi-Hole which may be interfering?

**Comment by julianwieg** [comment]
mhh it something to do with docker. pip install works just fine but from docker even with sudo it doesn't.   I recall a few weeks ago I tried running something from docker and the containers could not connect to the Internet from the VM. Need to troubleshoot docker it seems like :(
