### ISSUE TITLE
Add Aidan's key magic to the general knowledge section

### ISSUE THREAD

**Issue by Frichetten** [Hacking-the-Cloud/hackingthe.cloud#297]
Aidan Steele is a magic wizard. Gandalf better move over. Aidan shared [this](https://cloudsecurityforum.slack.com/archives/C6DN616HG/p1700015790826609) trick in the Cloud Security Slack and I think it would make for a great short article in the general knowledge section.

**Comment by Frichetten** [comment]
There is an invite system. If you like, I can send an invite to the email address you have listed on your GitHub account? I can't guarantee the admins will approve the request though.

**Comment by pjhavariotis** [comment]
Please send me an invitation to my GitHub account email address. Thanks!

**Comment by Frichetten** [comment]
Handled by #299
